'use client';
import {useEffect,useState,useRef} from 'react';
import {Accessibility,ArrowUpRight,ArrowRight,Download,RotateCcw,MapPin,Layers,Check,AlertTriangle,Route,ChevronRight,Wrench,Info,ShieldCheck} from 'lucide-react';
import {Switch} from '@/components/ui/switch';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {nodes,edges,profiles,initialScenario,exclusion,type Scenario,type Profile,type Analysis} from '@/lib/accesscut';
export default function Home(){
 const [scenario,setScenario]=useState<Scenario>(initialScenario),[result,setResult]=useState<Analysis|null>(null),[selected,setSelected]=useState('library'),[preview,setPreview]=useState<string|null>(null),[previewResult,setPreviewResult]=useState<Analysis|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(true),[elapsed,setElapsed]=useState(0),[notice,setNotice]=useState(''),[explain,setExplain]=useState(false);const ranking=useRef<HTMLDivElement>(null);
 useEffect(()=>{const c=new AbortController();setBusy(true);setResult(null);setError('');setPreview(null);setPreviewResult(null);const start=performance.now();fetch('/api/analyze',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(scenario),signal:c.signal}).then(async r=>{const data=await r.json() as Analysis & {error?:string};if(!r.ok)throw new Error(data.error);return data;}).then(data=>{setResult(data);setElapsed(Math.round(performance.now()-start));setBusy(false);}).catch(e=>{if(e.name!=='AbortError'){setError('Analysis could not load. Please retry.');setBusy(false);}});return()=>c.abort();},[scenario]);
 useEffect(()=>{if(!preview){setPreviewResult(null);return;}const c=new AbortController();setPreviewResult(null);fetch('/api/analyze',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...scenario,closed:scenario.closed.filter(id=>id!==preview)}),signal:c.signal}).then(async r=>{if(!r.ok)throw new Error();return r.json() as Promise<Analysis>;}).then(setPreviewResult).catch(e=>{if(e.name!=='AbortError')setError('Repair preview could not load. Please try again.');});return()=>c.abort();},[preview,scenario]);
 useEffect(()=>{const context=(document as Document&{modelContext?:{registerTool:(tool:unknown,options:unknown)=>Promise<void>}}).modelContext;if(!context)return;const c=new AbortController();try{Promise.resolve(context.registerTool({name:'read_accesscut_analysis',description:'Read the current campus access analysis and repair ranking.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:(input:unknown)=>{if(!input||typeof input!=='object'||Object.keys(input).length)throw new Error('Expected an empty object');if(busy||!result)throw new Error('Analysis is loading');return result;}},{signal:c.signal})).catch(()=>{});}catch{}return()=>c.abort();},[result,busy]);
 const shown=previewResult??result,displayScenario=previewResult?previewResult.scenario:scenario,destination=shown?.destinations.find(d=>d.id===selected),routeEdges=destination?.path??[],top=result?.repairs.find(r=>r.gain>0);
 const toggle=(id:string)=>setScenario(s=>({...s,closed:s.closed.includes(id)?s.closed.filter(x=>x!==id):[...s.closed,id]}));
 function exportReport(){if(!result||busy)return;const blob=new Blob([JSON.stringify({...result,provenance:'Synthetic campus fixture. Not surveyed or suitable for real navigation.',objective:'Maximize newly reachable destinations from the selected origin; equal weights; single repair only.',exportedAt:new Date().toISOString()},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='accesscut-analysis.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setNotice('Analysis report downloaded.');}
 return <div className="app-shell"><header className="topbar"><a className="brand" href="/" aria-label="AccessCut home"><span className="brand-icon"><Accessibility size={24}/></span>Access<span>Cut</span></a><div className="top-label">CAMPUS ACCESS PLANNING</div><span className="demo-badge"><span/>Interactive demo</span></header><main>
 <div className="page-heading"><div><div className="eyebrow">NORTHBRIDGE CAMPUS <span>/</span> REPAIR PLANNER</div><h1>A clearer path to access.</h1><p>Find the one repair that opens the most destinations.</p></div><button className="button secondary" disabled={!result||busy} onClick={exportReport}><Download size={16}/>Export analysis</button></div>
 <div className="workspace"><aside className="controls panel"><div className="section-heading"><span className="number">01</span><h2>Set the scenario</h2></div>
 <label id="profile-label" className="field-label">Access profile</label><Select value={scenario.profile} onValueChange={v=>setScenario(s=>({...s,profile:v as Profile}))}><SelectTrigger aria-labelledby="profile-label" className="full-select"><SelectValue/></SelectTrigger><SelectContent>{Object.entries(profiles).map(([id,p])=><SelectItem key={id} value={id}>{p.name}</SelectItem>)}</SelectContent></Select>
 <div className="profile-note"><Accessibility size={17}/><span>{profiles[scenario.profile].steps?'Stairs allowed':'No stairs'} · minimum {profiles[scenario.profile].width} cm width</span></div>
 <label id="origin-label" className="field-label">Starting point</label><Select value={scenario.origin} onValueChange={origin=>setScenario(s=>({...s,origin}))}><SelectTrigger aria-labelledby="origin-label" className="full-select"><SelectValue/></SelectTrigger><SelectContent>{nodes.map(n=><SelectItem key={n.id} value={n.id}>{n.name}</SelectItem>)}</SelectContent></Select>
 <div className="divider"/><div className="row-between"><h3>Reported closures</h3><span className="count-badge">{scenario.closed.length}</span></div><p className="small muted">Switch on a closure to see its impact.</p><div className="closures">{edges.filter(e=>e.repairable).map(e=><div className="closure" key={e.id}><div><label htmlFor={e.id}>{e.name}</label><span className={scenario.closed.includes(e.id)?'status closed':'status'}>{scenario.closed.includes(e.id)?'Unavailable':'Operational'}</span></div><Switch id={e.id} checked={scenario.closed.includes(e.id)} onCheckedChange={()=>toggle(e.id)} aria-label={`${e.name} unavailable`}/></div>)}</div>
 <button className="button primary find-repair" disabled={busy||!top} onClick={()=>{setPreview(top!.id);ranking.current?.scrollIntoView({behavior:'smooth',block:'nearest'});}}><Wrench size={17}/>Find best single repair<ArrowRight size={16}/></button><button className="reset" onClick={()=>{setScenario({...initialScenario});setSelected('library');setNotice('Demo scenario reset.');}}><RotateCcw size={14}/>Reset scenario</button><div className="data-note"><ShieldCheck size={18}/><div><strong>Conservative by design</strong><p>Unknown widths are excluded. Repairs reopen connections without changing their dimensions.</p></div></div></aside>
 <section className="map-panel panel" aria-label="Campus access map"><div className="map-heading"><div><span className="map-title">Northbridge campus</span><span className="map-subtitle">Schematic network · synthetic data</span></div><span className="map-tag"><Layers size={14}/>Access layer</span></div><div className="map-canvas" aria-busy={busy}><svg viewBox="0 0 860 610" role="group" aria-label="Interactive campus network. Choose a destination to inspect its route."><defs><pattern id="grid" width="24" height="24" patternUnits="userSpaceOnUse"><circle cx="1" cy="1" r="1" fill="#dce3e7"/></pattern></defs><rect width="860" height="610" fill="url(#grid)"/><rect x="328" y="184" width="129" height="244" rx="25" className="courtyard"/><text x="393" y="245" textAnchor="middle" className="area-label">CENTRAL</text><text x="393" y="264" textAnchor="middle" className="area-label">QUAD</text><text x="70" y="570" className="area-label">SOUTH CAMPUS</text><path d="M798 78V42m-8 10 8-10 8 10" stroke="#738190" fill="none" strokeWidth="2"/><text x="798" y="30" textAnchor="middle" className="area-label">N</text>
 {edges.map(e=>{const a=nodes.find(n=>n.id===e.from)!,b=nodes.find(n=>n.id===e.to)!,excluded=exclusion(e,displayScenario);return <g key={e.id}><line x1={a.x} y1={a.y} x2={b.x} y2={b.y} className={`map-edge ${excluded?'unavailable':''} ${e.width===null?'unknown':''} ${routeEdges.includes(e.id)?'route-active':''} ${previewResult&&preview===e.id?'repair-active':''}`}/>{e.repairable&&<g transform={`translate(${(a.x+b.x)/2},${(a.y+b.y)/2})`}><rect x="-15" y="-15" width="30" height="30" rx="8" fill={excluded?'#fff0ed':'#e5f4ed'} stroke={excluded?'#e5b0a6':'#93c9b0'}/><text textAnchor="middle" y="5" fill={excluded?'#b14e3b':'#226e51'} fontSize="18">{excluded?'×':'✓'}</text></g>}</g>;})}
 {nodes.map(n=>{const d=shown?.destinations.find(d=>d.id===n.id),chosen=n.id===selected,origin=n.id===scenario.origin;return <g key={n.id} role={n.destination?'button':undefined} tabIndex={n.destination?0:undefined} aria-label={n.destination?`${n.name}: ${d?.reachable?'reachable':'unreachable'}. Show route.`:undefined} onClick={()=>n.destination&&setSelected(n.id)} onKeyDown={e=>{if(n.destination&&(e.key==='Enter'||e.key===' ')){e.preventDefault();setSelected(n.id);}}} className={n.destination?'map-destination':''}>{chosen&&<circle cx={n.x} cy={n.y} r="27" fill="none" stroke="#24785a" strokeWidth="2" strokeDasharray="4 4"/>}<circle cx={n.x} cy={n.y} r={n.destination||origin?18:7} fill={origin?'#182f43':n.destination?(d?.reachable?'#24785a':'#fcfcfb'):'#fff'} stroke={n.destination&&!d?.reachable?'#cf7865':'#24785a'} strokeWidth="2"/>{(n.destination||origin)&&<text x={n.x} y={n.y+5} textAnchor="middle" fontSize="15" fontWeight="700" fill={origin||d?.reachable?'white':'#b65843'}>{origin?'S':d?.reachable?'✓':'!'}</text>}<text x={n.x} y={n.y+(n.destination||origin?42:26)} textAnchor="middle" className={n.destination?'node-label':'junction-label'}>{n.name}</text></g>;})}</svg><div className="map-legend"><span><i className="legend-line green"/>Open</span><span><i className="legend-line red"/>Excluded</span><span><i className="legend-line gray"/>Unverified</span></div></div><div className="map-footer"><span><Info size={14}/>Select a destination to inspect its route</span><span>Not to geographic scale</span></div></section>
 <aside className="insights"><div className="impact-card"><span className="eyebrow">{previewResult?'AFTER PROPOSED REPAIR':'CURRENT ACCESS'}</span><div className="impact-number">{shown?.reachable??'—'}<span>/ {shown?.total??6}</span></div><h2>destinations reachable</h2><div className="access-meter">{Array.from({length:6},(_,i)=><span key={i} className={i<(shown?.reachable??0)?'filled':''}/>)}</div><p>{previewResult?`${previewResult.reachable-(result?.reachable??0)} additional destinations with this repair.`:'From your selected starting point and access profile.'}</p></div><div className="destination-panel panel"><div className="section-heading"><Route size={17}/><h2>Destination routes</h2></div>{shown?.destinations.map(d=><button key={d.id} className={`destination-row ${selected===d.id?'selected':''}`} onClick={()=>setSelected(d.id)}><span className={`destination-state ${d.reachable?'yes':''}`}>{d.reachable?<Check size={13}/>:<span>—</span>}</span><span>{d.name}<small>{d.reachable?`${d.meters} m route`:'No supported route'}</small></span><ChevronRight size={14}/></button>)}</div></aside></div>
 {error&&<div role="alert" className="error-banner">{error}<button onClick={()=>setScenario(s=>({...s}))}>Retry</button></div>}<div className="analysis-status" role="status">{error?'Analysis unavailable':busy?'Recomputing access…':`Analysis complete · ${result?.computeMs??0} ms compute · ${elapsed} ms round trip`}{notice&&<span>{notice}</span>}</div>
 <div className="bottom-grid"><section className="panel repairs-panel" ref={ranking}><div className="row-between"><div className="section-heading"><span className="number">02</span><h2>Repair the connection. Restore access.</h2></div><span className="small muted">Single-repair comparison</span></div><p className="muted small">Ranked by newly reachable destinations. Equal weights; ties are alphabetical.</p>{!result?.repairs.length?<div className="empty-state"><Check size={24}/><div><strong>{busy?'Analyzing connections…':'No reported closures'}</strong><p>Profile constraints and unverified widths still apply.</p></div></div>:<div className="repair-list">{result?.repairs.map((r,index)=><div key={r.id} className={`repair-card ${preview===r.id?'is-preview':''}`}><div className="repair-rank">{String(index+1).padStart(2,'0')}</div><div className="repair-description"><div><h3>{r.name}</h3>{index===0&&r.gain>0&&<span className="recommended">TOP CHOICE</span>}</div><p>{r.gain?`Restores ${r.restored.join(' and ')}.`:r.stillExcluded??'No additional destinations become reachable.'}</p></div><div className="gain">+{r.gain}<span>destinations</span></div><button className="button secondary" disabled={busy} onClick={()=>setPreview(preview===r.id?null:r.id)}>{preview===r.id?'Close preview':'Preview'}<ArrowUpRight size={14}/></button></div>)}</div>}{preview&&<div className="preview-bar"><div><strong>Previewing {edges.find(e=>e.id===preview)?.name}</strong><p>{previewResult?'The map shows the repair. Your scenario is unchanged.':'Computing the repaired scenario…'}</p></div><button className="button primary" disabled={!previewResult||busy} onClick={()=>{setScenario(s=>({...s,closed:s.closed.filter(id=>id!==preview)}));setNotice('Repair applied to this simulated scenario.');}}>Apply to scenario<Check size={15}/></button></div>}</section>
 <section className="panel route-panel"><div className="section-heading"><span className="number">03</span><h2>Why this route?</h2></div><div className="route-target"><MapPin size={20}/><div><span className="small muted">{nodes.find(n=>n.id===scenario.origin)?.name} to</span><h3>{destination?.name??'Library'}</h3></div></div>{destination?.reachable?<><div className="route-summary"><strong>{destination.meters} m</strong><span>Shortest supported path</span></div><ol className="route-steps">{destination.path.length?destination.path.map(id=>{const e=edges.find(e=>e.id===id)!;return <li key={id}><span>{e.name}</span><small>{e.meters} m · {e.width} cm wide</small></li>}):<li>You are already at this destination.</li>}</ol></>:<div className="unreachable-note"><AlertTriangle size={20}/><div><strong>{busy?'Analyzing route…':'No supported route'}</strong><p>The current graph has no path meeting this profile. Preview a repair to see whether access can be restored.</p></div></div>}<button className="explain-toggle" onClick={()=>setExplain(!explain)} aria-expanded={explain}>{explain?'Hide':'Inspect'} excluded connections<ChevronRight size={15}/></button>{explain&&<ul className="excluded-list">{shown?.excluded.map(e=><li key={e.id}><strong>{e.name}</strong><span>{e.reason}</span></li>)}</ul>}</section></div>
 <footer className="page-footer"><span><ShieldCheck size={15}/>Transparent inputs. Reproducible decisions.</span><span>Synthetic campus v1 · Planning demonstration, not navigation guidance</span></footer></main></div>
}

